### ISSUE TITLE
SendDataMessage 前端怎么接收消息[问题]

### ISSUE THREAD

**Issue by Aries051211** [XuanchenLin/NanUI#351]
**NanUI/Formium版本**
**NanUI/Formium Version**

**操作系统 / Windows Version**

**问题描述 / QUESTION**

**Comment by XuanchenLin** [comment]
这是一个实验性的功能，我并没有共开。如果想尝试，那么前端请用 formium.onDataMessageReceived(function(msg) {}) 注册接收函数来接收后端通过 SendDataMessage 发过来的 JSON 字符，反之亦然~
