### ISSUE TITLE
希望添加网络拦截功能[REQUEST]

### ISSUE THREAD

**Issue by Nahts** [XuanchenLin/NanUI#357]
在cefsharp中 可以重载拦截网络资源 如：https://juejin.cn/post/6949531300176871438
在Webview2中，可以添加资源请求过滤器进行拦截，如：https://www.likecs.com/ask-112753.html
希望NanUI也能够支持类似功能，这样我们就可以实现任意网络请求发起后，返回内容的处理了。比如：访问 访问任意网站的api请求，我们都把返回的json对象转大写了，或者修改返回的对象内容...
如上，希望作者能有兴趣

**Comment by XuanchenLin** [comment]
NanUI基于CefGlue，既然CefSharp能够实现拦截，原则上CefGlue同样也能够实现。
在GetResourceRequestHandler事件中构造CefResourceRequestHandler并在其中的GetResourceResponseFilter重载方法中构造自己的ResponseFilter即可实现拦截和替换。
