### ISSUE TITLE
[问题]网页中运行的js有请求打开麦克风的功能，如何再NanUI下默认允许网页打开麦克风语音输入？

### ISSUE THREAD

**Issue by dz009git** [XuanchenLin/NanUI#358]
**NanUI/Formium版本**
0.8.80
**NanUI/Formium Version**

**操作系统 / Windows Version**
windows 7 64x

**问题描述 / QUESTION**
网页中运行的js有请求打开麦克风的功能，如何再NanUI下默认允许网页打开麦克风语音输入？

**Comment by XuanchenLin** [comment]
在某个Chromium的更新之后，一切有关隐私的接口都需要在ssl链接下才可以实现，比如麦克风，摄像头什么的。
所以要么你的网页使用ssl链接访问，要么通过unsafely-treat-insecure-origin-as-secure参数把你的网页加到白名单里让其被当作ssl连接，这样就能打开摄像头或者麦克风。
另外我记得要启动这些功能还需要加上enable-media-stream参数。
