### ISSUE TITLE
[问题]请教如何做exe单文件打包

### ISSUE THREAD

**Issue by BruceLuo2** [XuanchenLin/NanUI#359]
请教如何做exe单文件打包发布?

**Comment by XuanchenLin** [comment]
如果一定要用单文件打包，请将CEF的运行时文件放置到 *%PROGRAMDATA%\Net** Dimension Studio\NanUI\90.6.7\* 目录下，目录结构与普通发布模式的 *fx* 文件夹一致。
如图：
![image](https://github.com/XuanchenLin/NanUI/assets/16586330/48f5d1ef-1cee-4363-9ee6-70cfa4371d28)
