### ISSUE TITLE
请问在前端上传大文件或者大的请求json字符串应该使用哪种方式？

### ISSUE THREAD

**Issue by hanjunjun** [XuanchenLin/NanUI#360]
问题描述：
1.我有一个很大的excel文件大概有10万行，需要通过页面提交之后c#处理。
我看框架提供了注册 JavaScript 对象和app.UseDataServiceResource("http", "api.app.local")api接口映射，我应该使用哪种方式比较合理，不会出bug？

**Comment by XuanchenLin** [comment]
你点上传的时候dataservice里面的file里就拿到上传文件的物理路径，既然拿到了物理路径，要进行任何操作都跟前端没有关系了，用C#处理即可。
