### ISSUE TITLE
[REQUEST] English docs

### ISSUE THREAD

**Issue by CypherPotato** [XuanchenLin/NanUI#363]
I see a lot of potential in this project, it seems to be very cool. It would be interesting if there was an internationalized documentation to use this FW, in English for example.

Anyway, congrats! It's a really cool project. It's good to see that we have good alternatives to electron.

**Comment by XuanchenLin** [comment]
The documentation is now available in English. But I translated these documents from Chinese using Google Translate, so there are bound to be errors in the documents.

Feel free to submit PRs to improve the English documentation!
