### ISSUE TITLE
太难了，老铁😂

### ISSUE THREAD

**Issue by yourbusiness** [XuanchenLin/NanUI#369]

**Comment by suzhenghui-sky** [comment]
是啊！直接跨行做销售。

**Comment by pheromone** [comment]
廉价的中国人民，哎。。。。。

**Comment by pheromone** [comment]
廉价劳动力大国人民~哎。。。。。。。

**Comment by AddASecond** [comment]
为什么不卖显卡呢？会不会比刚才赚钱

**Comment by dh-free** [comment]
真难啊

**Comment by wlpsunny** [comment]
是继承家族产业了吗？跨度太大了吧

**Comment by xiangyuecn** [comment]
https://www.douyin.com/video/7288267039657987383 多难的UI，我先瞧瞧

**Comment by XuanchenLin** [comment]
> https://www.douyin.com/video/7288267039657987383 多难的UI，我先瞧瞧

难，确实难，哈哈

**Comment by XuanchenLin** [comment]
感谢各位支持，但是还是请别再issues里讲这个😂

欢迎到discussions里灌水~

这个我先关闭了

**Comment by bugfix2020** [comment]
难啊老兄 这套UI感觉有点生不逢时
就像是layui的作者贤心一样 一直坚持”返璞归真“ 但是收益人群是后端开发者 在前后端分离的潮流下 三大框架已经占据了前端市场 这种只针对特定人群服务的框架注定是会落幕的

也正如作者这套UI 同样是针对特定人群服务 但在Chrome v8的加持下是electron开发客户端应用已经顺应潮流且占据市场 这套UI最终也将落幕 但不可否认的是这套UI为曾为开发者带来了便捷
