### ISSUE TITLE
Add Docker 

### ISSUE THREAD

**Issue by Durgesh4993** [XuanchenLin/NanUI#371]
Sir can i add docker in Repository, which help to deploy applications quickly

**Comment by XuanchenLin** [comment]
> Sir can i add docker in Repository, which help to deploy applications quickly

Yes, you can. Although I don't understand how to speed up the deployment of application by using docker, but any kinds of contribution are welcomed.

**Comment by Durgesh4993** [comment]
@XuanchenLin Thank you
