### ISSUE TITLE
Embedding an ASP.NET Core Website Application with NanUI?

### ISSUE THREAD

**Issue by zztss** [XuanchenLin/NanUI#375]
How can I use NanUI to embed an ASP.NET Core website application, as the current examples are all about hosting static HTML or URLs?

**Comment by XuanchenLin** [comment]
You should not "embed" an ASP.NET Core website into a NanUI application, it is not recommended. You should compile the asp.net core website into a stand-alone executable file, and use the Process.Start method to load the asp.net core application when NanUI's main process starts. It can be used as a child process.

But I still strongly recommend using static HTML as the user interface,  embedding these static files into application as resources, and using fetch or axios to load data from the server.

**Comment by XuanchenLin** [comment]
为何不说中文，我以为是老外😂
