### ISSUE TITLE
文档都失效了吗？

### ISSUE THREAD

**Issue by lycoris-xmin** [XuanchenLin/NanUI#376]
刚知道这个项目，想学习一下，找了好多文档，要么就是文档链接失效，要么就是版本对不上就是找不到各种nuget包。

一个js对象使用`RegisterJavaScriptObject`注册了，但是在js里使用`formium`也获取不到，直接使用名字也获取不到；
找到一个旧版本看使用`formium.external`直接就是`undefined`，没有这个属性；
都不知道怎么解决。

**Comment by XuanchenLin** [comment]
https://github.com/XuanchenLin/NanUI/tree/0.9.109

NuGet当前版本的分支，文档也对应这个分支。此分支的demo目录里是示例项目，示例项目已经对各种功能和接口进行了介绍，请自行拉代码下来看。

现在主分支是1.0的，但是还未开发完成，也没有发布过nuget包，1.0由于我个人原因暂时无力继续，要用的话目前可选的稳定版本只有0.9.109
