### ISSUE TITLE
Feature: Adding contribution section to the Readme.md file.

### ISSUE THREAD

**Issue by Kalyanimhala** [XuanchenLin/NanUI#380]
There is no Contributors section in readme file .
As we know Contributions are what make the open-source community such an amazing place to learn, inspire, and create.
The Contributors section in a README.md file is important as it acknowledges and gives credit to those who have contributed to a project, fosters community and collaboration, adds transparency and accountability, and helps document the project's history for current and future maintainers. It also serves as a form of recognition, motivating contributors to continue their efforts.
![contributors](https://github.com/XuanchenLin/NanUI/assets/147402107/e5d26bb9-dfaa-4e84-9d1a-fdf9748100bf)

**Comment by Kalyanimhala** [comment]
@XuanchenLin  Kindly assign me this issue, I want to work on it. Thank You!!

**Comment by XuanchenLin** [comment]
If this is useful then you are welcome to submit a PR.
