### ISSUE TITLE
builder.UseAsEmbedded

### ISSUE THREAD

**Issue by gaoconggit** [XuanchenLin/NanUI#383]
UseAsEmbedded 这个扩展方法找不到，master分支

**Comment by gaoconggit** [comment]
https://github.com/XuanchenLin/NanUI/blob/master/docs/Forms/Control-Style.md
---
这个扩展方法 UseAsEmbedded  怎么引入？

**Comment by XuanchenLin** [comment]
nuget卸载nanui包，并安装winformium包。

**Comment by nightytz** [comment]
![image](https://github.com/XuanchenLin/NanUI/assets/100210248/e8b213a0-85f3-46bf-b114-34213e42b48a)

**Comment by nightytz** [comment]
![image](https://github.com/XuanchenLin/NanUI/assets/100210248/29106587-9a17-4b27-afc3-9cd652fc1124)
为什么会这样
